# Generated by Django 3.2.9 on 2021-11-29 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Filmes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_do_filme', models.CharField(max_length=200)),
                ('autor_do_filme', models.CharField(max_length=200)),
                ('data_publicada_do_filme', models.DateTimeField(verbose_name='Publicado em')),
                ('genero_do_filme', models.CharField(max_length=100)),
                ('classificacao_do_filme', models.SmallIntegerField()),
                ('elenco_do_filme', models.CharField(max_length=5000)),
            ],
        ),
        migrations.CreateModel(
            name='HQs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_da_hq', models.CharField(max_length=200)),
                ('data_publicada_da_hq', models.DateTimeField(verbose_name='Publicado em')),
                ('genero_da_hq', models.CharField(max_length=100)),
                ('numero_da_hq', models.SmallIntegerField()),
                ('editora_da_hq', models.CharField(max_length=200)),
                ('personagens_da_hq', models.CharField(max_length=5000)),
                ('quantidade_de_paginas', models.SmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Noticias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo_da_noticia', models.TextField()),
                ('noticias', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Opinioes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_da_obra', models.CharField(max_length=200)),
                ('opiniao', models.CharField(max_length=9999)),
            ],
        ),
        migrations.CreateModel(
            name='Series',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_da_serie', models.CharField(max_length=200)),
                ('autor_da_serie', models.CharField(max_length=200)),
                ('data_publicada_da_serie', models.DateTimeField(verbose_name='Publicado em')),
                ('genero_da_serie', models.CharField(max_length=100)),
                ('classificacao_da_serie', models.SmallIntegerField()),
                ('elenco_da_serie', models.CharField(max_length=5000)),
            ],
        ),
    ]
