# Generated by Django 3.2.9 on 2021-11-29 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acoes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticias',
            name='titulo_da_noticia',
            field=models.TextField(blank=True),
        ),
    ]
