# Generated by Django 3.2.9 on 2021-11-29 22:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('acoes', '0002_alter_noticias_titulo_da_noticia'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Noticias',
        ),
    ]
