# Generated by Django 3.2.9 on 2021-11-29 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acoes', '0003_delete_noticias'),
    ]

    operations = [
        migrations.CreateModel(
            name='Noticias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo_da_noticia', models.TextField(blank=True)),
                ('noticias', models.TextField()),
            ],
        ),
    ]
